cluster:
  name: ci-test-cluster

externalServices:
  prometheus:
    secret:
      create: false
      name: prometheus
      namespace: prometheus
    queryEndpoint: /api/v1/query
    writeEndpoint: /api/v1/write
    tls:
      insecure_skip_verify: true
  loki:
    host: http://loki.loki.svc:3100
    tenantId: 1
    basicAuth:
      username: loki
      password: lokipassword
  tempo:
    host: tempo.tempo.svc:4317
    tlsOptions: |-
      insecure             = true
      insecure_skip_verify = true

metrics:
  apiserver:
    enabled: true

test:
  extraQueries:
  - query: kube_deployment_spec_replicas{cluster="ci-test-cluster"}

opencost:
  prometheus:
    secret_name: prometheus
    username_key: username
    password_key: password
    external:
      url: http://prometheus-server.prometheus.svc:80/api/v1
